name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout profile repository
        uses: actions/checkout@v7

      - name: Generate 3D profile contribution graph
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: RazordousJR

      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Generate 3D contribution graph
          file_pattern: profile-3d-contrib/*.svg
